<?php

namespace Database\Seeders;

use App\Enums\Common\Rarity;
use App\Enums\Equipment\EquipmentSlot;
use App\Enums\Equipment\SubWeaponCategory;
use App\Enums\Equipment\WeaponCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EquipmentSeeder extends Seeder
{
    public function run(): void
    {
        $timestamp = now();

        DB::table('equipments')->upsert([
            [
                'item_id' => 'eq_hammer_001',
                'equipment_slot' => EquipmentSlot::MAIN_WEAPON->value,
                'rarity' => Rarity::COMMON->value,
                'level_required' => 1,
                'weapon_category' => WeaponCategory::HAMMER->value,
                'sub_weapon_category' => null,
                'is_two_handed' => false,
                'attack' => 12,
                'physical_defense' => 0,
                'magic_defense' => 0,
                'hp' => 0,
                'mana' => 0,
                'attack_speed' => 10,
                'crit_rate' => 2,
                'spell_power' => 0,
                'is_enabled' => true,
                'sort_order' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'item_id' => 'eq_shield_001',
                'equipment_slot' => EquipmentSlot::SUB_WEAPON->value,
                'rarity' => Rarity::COMMON->value,
                'level_required' => 1,
                'weapon_category' => null,
                'sub_weapon_category' => SubWeaponCategory::SHIELD->value,
                'is_two_handed' => false,
                'attack' => 0,
                'physical_defense' => 8,
                'magic_defense' => 2,
                'hp' => 10,
                'mana' => 0,
                'attack_speed' => 0,
                'crit_rate' => 0,
                'spell_power' => 0,
                'is_enabled' => true,
                'sort_order' => 2,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'item_id' => 'eq_staff_001',
                'equipment_slot' => EquipmentSlot::MAIN_WEAPON->value,
                'rarity' => Rarity::RARE->value,
                'level_required' => 1,
                'weapon_category' => WeaponCategory::STAFF->value,
                'sub_weapon_category' => null,
                'is_two_handed' => true,
                'attack' => 8,
                'physical_defense' => 0,
                'magic_defense' => 0,
                'hp' => 0,
                'mana' => 12,
                'attack_speed' => 9,
                'crit_rate' => 3,
                'spell_power' => 15,
                'is_enabled' => true,
                'sort_order' => 3,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'item_id' => 'eq_armor_001',
                'equipment_slot' => EquipmentSlot::ARMOR->value,
                'rarity' => Rarity::COMMON->value,
                'level_required' => 1,
                'weapon_category' => null,
                'sub_weapon_category' => null,
                'is_two_handed' => false,
                'attack' => 0,
                'physical_defense' => 12,
                'magic_defense' => 4,
                'hp' => 20,
                'mana' => 0,
                'attack_speed' => 0,
                'crit_rate' => 0,
                'spell_power' => 0,
                'is_enabled' => true,
                'sort_order' => 4,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'item_id' => 'eq_ring_001',
                'equipment_slot' => EquipmentSlot::RING->value,
                'rarity' => Rarity::RARE->value,
                'level_required' => 1,
                'weapon_category' => null,
                'sub_weapon_category' => null,
                'is_two_handed' => false,
                'attack' => 2,
                'physical_defense' => 1,
                'magic_defense' => 1,
                'hp' => 6,
                'mana' => 4,
                'attack_speed' => 1,
                'crit_rate' => 4,
                'spell_power' => 2,
                'is_enabled' => true,
                'sort_order' => 5,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'item_id' => 'eq_bracelet_001',
                'equipment_slot' => EquipmentSlot::BRACELET->value,
                'rarity' => Rarity::RARE->value,
                'level_required' => 1,
                'weapon_category' => null,
                'sub_weapon_category' => null,
                'is_two_handed' => false,
                'attack' => 0,
                'physical_defense' => 2,
                'magic_defense' => 4,
                'hp' => 4,
                'mana' => 8,
                'attack_speed' => 0,
                'crit_rate' => 1,
                'spell_power' => 5,
                'is_enabled' => true,
                'sort_order' => 6,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
        ], ['item_id'], [
            'equipment_slot',
            'rarity',
            'level_required',
            'weapon_category',
            'sub_weapon_category',
            'is_two_handed',
            'attack',
            'physical_defense',
            'magic_defense',
            'hp',
            'mana',
            'attack_speed',
            'crit_rate',
            'spell_power',
            'is_enabled',
            'sort_order',
            'updated_at',
        ]);
    }
}
